version: "3.8"

services:
ulloa:
image: ghcr.io/martinsangucho/ulloa:1.0.5
deploy:
replicas: 1
labels:
- "traefik.enable=true"
- "traefik.http.routers.ulloa.entrypoints=http"
- "traefik.http.routers.ulloa.rule=Host(ulloa.byronrm.com)"
- "traefik.http.middlewares.ulloa-https-redirect.redirectscheme.scheme=https"
- "traefik.http.routers.ulloa.middlewares=ulloa-https-redirect"
- "traefik.http.routers.ulloa-secure.entrypoints=https"
- "traefik.http.routers.ulloa-secure.rule=Host(ulloa.byronrm.com)"
- "traefik.http.routers.ulloa-secure.tls=true"
- "traefik.http.routers.ulloa-secure.tls.certresolver=http"
- "traefik.http.routers.ulloa-secure.service=ulloa"
- "traefik.http.services.ulloa.loadbalancer.server.port=5000"
- "traefik.docker.network=traefik-public"
networks:
- traefik-public

networks:
traefik-public:
external: true