version: '3.9'

services:
  # 1. NOMBRE DEL SERVICIO: CRITERIO SEGUNDO APELLIDO
  ulloa:
    # 2. IMAGEN: CRITERIO SEGUNDO APELLIDO y VERSIÓN
    image: ghcr.io/martinsangucho/ulloa:1.0.5
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
      labels:
        # Habilitar Traefik
        - "traefik.enable=true"
        
        # --- HTTP Router (Redirección a HTTPS) ---
        - "traefik.http.routers.ulloa.entrypoints=http"
        # 3. CRITERIO SUBDOMINIO: Host correcto
        - "traefik.http.routers.ulloa.rule=Host(`ulloa.byronrm.com`)" 
        - "traefik.http.middlewares.ulloa-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.ulloa.middlewares=ulloa-https-redirect"

        # --- HTTPS Router (Servicio Seguro) ---
        - "traefik.http.routers.ulloa-secure.entrypoints=https"
        # 3. CRITERIO SUBDOMINIO: Host correcto
        - "traefik.http.routers.ulloa-secure.rule=Host(`ulloa.byronrm.com`)"
        - "traefik.http.routers.ulloa-secure.tls=true"
        - "traefik.http.routers.ulloa-secure.tls.certresolver=http"
        - "traefik.http.routers.ulloa-secure.service=ulloa"
        
        # Servicio y Puerto interno de Flask (5000 por defecto)
        - "traefik.http.services.ulloa.loadbalancer.server.port=5000"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true